export const INDUSTRIES = [
  "Data Analytics",
  "E-commerce",
  "Education",
  "Finance",
  "Fitness",
  "Healthcare",
  "Industrial",
  "Logistics",
  "Machine Learning",
  "Marketing",
  "Retail",
  "Telecommunications",
  "Technology",
  "Transportation",
  "Other",
];
