export const SKILLS = [
  // Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Rust",
  "Go",
  "R",
  "MATLAB",
  "SQL",
  "Scala",
  "Perl",
  "Dart",
  "Haskell",
  "Lua",

  // Web Development
  "HTML/CSS",
  "Sass/SCSS",
  "Tailwind CSS",
  "Bootstrap",
  "jQuery",
  "AJAX",
  "RESTful APIs",
  "GraphQL",
  "WebSockets",
  "Responsive Design",
  "SEO",
  "Web Accessibility",
  "Cross-Browser Compatibility",
  "Web Security",
  "Progressive Web Apps",

  // Frontend Frameworks & Libraries
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Backbone.js",
  "Ember.js",
  "Redux",
  "MobX",

  // Backend Development
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET Core",
  "Spring Boot",
  "Phoenix (Elixir)",
  "NestJS",
  "Hapi.js",
  "Koa.js",

  // Databases generic
  "NoSQL",

  // Databases specific
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "Firebase",
  "Cassandra",
  "Oracle Database",
  "SQL Server",
  "CouchDB",
  "Neo4j",
  "DynamoDB",
  "Elasticsearch",
  "MariaDB",
  "SQLite",

  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "Jenkins",
  "CI/CD",
  "CircleCI",
  "Travis CI",
  "Ansible",
  "Terraform",
  "AWS",
  "Google Cloud Platform",
  "Microsoft Azure",
  "OpenStack",
  "Cloud Foundry",
  "Serverless Architecture",
  "NGINX",
  "Apache",

  // Testing & QA
  "Jest",
  "Mocha",
  "Jasmine",
  "Cypress",
  "Selenium",
  "Puppeteer",
  "Postman",
  "JUnit",
  "TestNG",
  "Cucumber",
  "RSpec",
  "Enzyme",
  "PyTest",
  "Karma",
  "Load Testing",

  // Mobile Development
  "React Native",
  "Flutter",
  "Objective-C",
  "Xamarin",
  "Ionic",
  "NativeScript",
  "ARKit",
  "Android SDK",
  "CoreData",
  "Realm",

  // Data Science & Machine Learning
  "Pandas",
  "NumPy",
  "SciPy",
  "Scikit-Learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Natural Language Processing",
  "OpenCV",
  "Data Visualization",
  "D3.js",
  "Machine Learning",
  "Big Data",
  "Tableau",
  "Power BI",

  // Version Control
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Mercurial",
  "SVN",

  // Project Management & Collaboration
  "Agile Methodology",
  "Scrum",
  "Kanban",
  "JIRA",

  // System Administration & Networking
  "Linux/Unix Administration",
  "Windows Server",
  "Bash/Shell Scripting",
  "PowerShell",
  "Load Balancing",
  "VPNs",
  "Firewall Configuration",
  "SSL/TLS Encryption",
  "Network Monitoring",

  // Other Tools & Technologies
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Zeplin",
  "Swagger/OpenAPI",
  "Webpack",
  "Parcel",
  "Babel",
  "Vite",
  "Linting Tools",
  "Markdown",
  "UML Diagrams",
  "Jira",
];
